[package]
name = "uzfs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[workspace]
members = ["uzfs-sys"]

[build-dependencies]
bindgen = "0.60"
pkg-config = "0.3"
uzfs-sys = { path = "uzfs-sys", version = "0.1.0" }

[dependencies]
cstr-argument = "0.1"
uzfs-sys = { path = "uzfs-sys", version = "0.1.0" }
tempfile = "3.3.0"

[dev-dependencies]
criterion = "0.3"
env_logger="0.9.0"
test-log = "0.2.8"
serial_test = { version = "1.0.0" }

[[bench]]
name = "uzfs-bench"
path = "src/bench.rs"
harness = false
