[package]
name = "uzfs-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
pkg-config = "0.3"
build-env = "0.3"
bindgen = "0.60"
project-root = "0.2"

[dependencies]
libc = "0.2"

[lib]
crate-type = ["rlib"]
