[package]
name = "uzfs"
version = "0.1.0"
edition = "2021"
links = "uzfs"

[build-dependencies]
pkg-config = "0.3"
build-env = "0.3"
uzfs-sys = { path = "../uzfs-sys", version = "0.1.0" }

[dependencies]
uzfs-sys = { path = "../uzfs-sys", version = "0.1.0" }
cstr-argument = "0.1"
