name: CI

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly-2024-09-09]

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install uuid-dev libblkid-dev libudev-dev libtirpc-dev
    - name: Install rustfmt
      run: rustup component add rustfmt
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    - uses: Swatinem/rust-cache@v1
    - run: cargo fmt --all -- --check
    - name: Check all targets
      run: make
    - name: Run tests
      run: make test
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
